---
title: "Formation-R-perfectionnement"
subtitle: "Module Création de graphiques avec ggplot2"
date: today
date-format: "DD/MM/YYYY"
author: "SSP/DEMESIS"
description: |
  Support de formation R-perfectionnement : Module Création de graphiques avec ggplot2 au MASA
slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide
fig-cap-location: bottom
# toc: true
# toc-title: Sommaire
# toc-depth: 1
# toc-float: true
#multiplex: true
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
  markdown: 
    wrap: 72
---

## Sommaire

|                                              |                              |
|-------------------------------------------|-----------------------------|
| 1 - Le package ggplot2                       | 8 - Les courbes              |
| 2 - Initialisation d'un graphique            | 9 - Les camemberts           |
| 3 - Les différentes géométries de graphiques | 10 - Les boîtes à moustaches |
| 4 - Croisement avec une autre variable       | 11 - Ajout de libellés       |
| 5 - Les diagrammes en barres                 | 12 - Habillage du graphique  |
| 6 - Les histogrammes                         | 13 - Sauvegarde du graphique |
| 7 - Les nuages de points                     | 14 - Liens                   |

## Avant-propos

<br>

Ce diaporama de formation a été rédigé dans le but d'être le support
visuel des formations dispensées au
[MASA](https://agreste.agriculture.gouv.fr/).

Ces formations s'adressent à des agents qui ont suivi **la formation R
initiation**.\

## Avant-propos

Elles sont données en présentiel sur une durée **de trois journée**, les
modules de cette formation sont ajustables suivants le choix des agents.

::: callout-note
## Champ couvert par cette formation

**Ce support couvre les rappels et complèments sur R et l'environnement
du Minsitère.**

Pour information, Les Modules de la formation R-perfectionnement sont:

-   01 - Module Rappels

-   02 - Module Fonctions

-   03 - Module Cartes statiques et interactives

-   04 - Module Création de graphiques avec ggplot2

-   05 - Module Quarto

-   06 - Module Parquet

-   07 - Module Initiation à l'écriture d'applications Shiny

Ils sont orientés pour être utiles aux agents du SSM MASA et se
concentrent sur une utilisation de R via
[RStudio](https://posit.co/download/rstudio-desktop/) qui est mise à
disposition des agents sur la plateforme interne Cerise basée sur
RStudio Workbench.
:::

{{< include 01_contexte.qmd >}}

{{< include 02_presentation.qmd >}}

{{< include 03_pourquoifaire.qmd >}}

{{< include 04_notionsprealables.qmd >}}

{{< include 05_fonctionnalites_partie1.qmd >}}

{{< include 06_fonctionnalites_partie2.qmd >}}

{{< include 07_astuces.qmd >}}
